stages:
  download:
    cmd: python3 ass_3/src/download.py
    deps:
    - ass_3/src/download.py
    params:
    - download.n_loc
    - download.year
    outs:
    - ass_3/data/
  prepare:
    cmd: python3 ass_3/src/prepare.py ass_3/data/
    deps:
    - ass_3/data/
    - ass_3/src/prepare.py
    outs:
    - ass_3/prepared
  process:
    cmd: python3 ass_3/src/process.py ass_3/data/ ass_3/prepared/
    deps:
    - ass_3/data/
    - ass_3/prepared/
    - ass_3/src/process.py
    outs:
    - ass_3/computed
